### ISSUE TITLE
Doc upload error printed in document content: Java Runtime out of mem

### ISSUE THREAD

**Issue by justacks** [rotblauer/openbound#1]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e1860000, 196608, 0) failed; error='Cannot allocate memory' (errno=12) # # There is insufficient memory for the Java Runtime Environment to continue. # Native memory allocation (malloc) failed to allocate 196608 bytes for committing reserved memory. # An error report file with more information is saved as: # /home/deploy/apps/openbound/releases/20170404200911/hs_err_pid17165.log

![screen shot 2017-05-10 at 5 42 20 pm](https://cloud.githubusercontent.com/assets/10282200/25924506/9e9a6374-35a8-11e7-8543-2269240ed67d.png)

**Comment by whilei** [comment]
http://openbound.org/projects/4ba518c2-1a95-472a-84fa-d9cead075c41

**Comment by whilei** [comment]
doubled server size... possible solve. reopen if occurs again
