### ISSUE TITLE
Add "Security" section (with terms and conditions?)

### ISSUE THREAD

**Issue by justacks** [rotblauer/openbound#20]
A lack of security info was pointed out by Kendra:

"It should privately send passwords, at least.  A mention of password encryption also makes me happy.  NOTE: I am *SUPER* not an expert in this, so I’d take Is’ word over mine but it makes me anxious setting up an account without at least minimal cover through https"

I would write it if I could, but I think maybe more up your alley/lingo/knowledge base.

**Comment by whilei** [comment]
Resolved in e1ce7e4.
See https://openbound.org.
