### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by jlanej** [rotblauer/openbound#29]
> https://openbound.org

->  Unable to connect

**Comment by whilei** [comment]
Can confirm.

**Comment by jlanej** [comment]
Need 4 more confirmation

**Comment by jlanej** [comment]
Can confirm

**Comment by whilei** [comment]
bump

**Comment by jlanej** [comment]
bump

**Comment by jlanej** [comment]
![](https://media.giphy.com/media/IP30yHlCkN8ha/giphy.gif)

**Comment by whilei** [comment]
may be an expired certificate

**Comment by whilei** [comment]
`too_many_redirects`. calling it improvement

**Comment by whilei** [comment]
resolved with 755704d  

_note_: had to use 
```shell
sudo service nginx restart
```
after deploy to kick changes in for `nginx`
