### ISSUE TITLE
Number of total works in libe! 

### ISSUE THREAD

**Issue by justacks** [rotblauer/openbound#4]
Running number of all works submitted at the top somehow would be awesome: used to that in google search results, etc. Feels like searching blind right meow, would trust it more as a new (or returning) user if I new how big of a space I am in. 

Also a GREAT way to get people to contribute, otherwise it seems like putting your paper into another black hole.

**Comment by whilei** [comment]
Resolved in 9252f13. It's small, but its something.

TODO: implement projects count for users and school pages.
